/*				DATA CLEANING				*/
SELECT * FROM [Pizza Sales].dbo.PIZZA_SALES

-- STANDARDIZE DATE FORMAT (ORDER_TIME COLUMN)
ALTER TABLE [Pizza Sales].dbo.PIZZA_SALES
ALTER COLUMN ORDER_TIME TIME(0)

UPDATE [Pizza Sales].dbo.PIZZA_SALES
SET ORDER_TIME = CAST(ORDER_TIME AS TIME(0))

-- A. KPI's REQUIREMENT

	-- 1. TOTAL REVENUE
	SELECT CONVERT(DECIMAL(10,1),SUM(TOTAL_PRICE)) AS TOTAL_REVENUE FROM [Pizza Sales].dbo.PIZZA_SALES

	-- 2. SALES PER ORDER
	SELECT CONVERT(DECIMAL(10,1), SUM(TOTAL_PRICE)/COUNT(DISTINCT ORDER_ID)) AS AVERAGE_REVENUE FROM [Pizza Sales].dbo.PIZZA_SALES

	-- 3. TOTAL PIZZAS SOLD
	SELECT SUM(QUANTITY) AS SOLD_QUANTITY FROM [Pizza Sales].dbo.PIZZA_SALES

	-- 4. TOTAL ORDERS
	SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM [Pizza Sales].dbo.PIZZA_SALES

	-- 5. AVERAGE PIZZAS PER ORDER
	SELECT CONVERT(DECIMAL(10,2), CONVERT(DECIMAL(10,2), SUM(QUANTITY))/COUNT(DISTINCT ORDER_ID)) AS AVG_PIZZA_PER_ORDER FROM [Pizza Sales].dbo.PIZZA_SALES

-- B. SALES TREND

	-- 1. DAILY TREND
	SELECT DATENAME(DW, ORDER_DATE) AS ORDER_DAY, COUNT(DISTINCT ORDER_ID) AS NUM_OF_ORDERS
	FROM [Pizza Sales].dbo.PIZZA_SALES
	GROUP BY DATENAME(DW, ORDER_DATE), DATEPART (DW, ORDER_DATE)
	ORDER BY DATEPART(DW, ORDER_DATE)

	-- 2. HOURLY TREND
	SELECT CONCAT(DATEPART(HH, ORDER_TIME), ':00 -', DATEPART(HH,ORDER_TIME) + 1, ':00') AS ORDER_HOUR, COUNT(DISTINCT ORDER_ID) AS NUM_OF_ORDERS
	FROM [Pizza Sales].dbo.PIZZA_SALES
	GROUP BY DATENAME(HH, ORDER_TIME), DATEPART(HH, ORDER_TIME)
	ORDER BY DATEPART(HH, ORDER_TIME)

-- C. PIZZAS SALES BY CATEGORY AND SIZE

	-- 1. PERCENTAGE OF SALES BY PIZZA CATEGORY
	SELECT PIZZA_CATEGORY, CONCAT(CONVERT(DECIMAL(10,2), SUM(TOTAL_PRICE)*100/(SELECT SUM(TOTAL_PRICE) FROM [Pizza Sales].dbo.PIZZA_SALES)),'%') AS PERCENTAGES
	FROM [Pizza Sales].dbo.PIZZA_SALES
	GROUP BY PIZZA_CATEGORY

	-- 2. PERCENTAGE OF SALES BY PIZZA SIZE
	SELECT PIZZA_SIZE, CONCAT(CONVERT(DECIMAL(10,2), SUM(TOTAL_PRICE)*100/(SELECT SUM(TOTAL_PRICE) FROM [Pizza Sales].dbo.PIZZA_SALES)),'%') AS PERCENTAGES
	FROM [Pizza Sales].dbo.PIZZA_SALES
	GROUP BY PIZZA_SIZE

	-- 3. TOTAL PIZZAS SOLD BY PIZZA CATEGORY
	SELECT PIZZA_CATEGORY, SUM(QUANTITY) AS TOTAL_SOLD
	FROM [Pizza Sales].dbo.PIZZA_SALES
	GROUP BY PIZZA_CATEGORY

-- D. PRODUCT PERFORMANCE

	-- 1. TOP 5 PIZZAS BY TOTAL ORDERS
	SELECT TOP 5 PIZZA_NAME, SUM(QUANTITY)
	FROM [Pizza Sales].dbo.PIZZA_SALES
	GROUP BY PIZZA_NAME
	ORDER BY SUM(QUANTITY) DESC

	-- 2. BOTTOM 5 PIZZA BY TOTAL ORDERS
	SELECT TOP 5 PIZZA_NAME, SUM(QUANTITY)
	FROM [Pizza Sales].dbo.PIZZA_SALES
	GROUP BY PIZZA_NAME
	ORDER BY SUM(QUANTITY) ASC

-- CREATE A VIRTUAL TABLE FOR VISUALIZATION 
CREATE VIEW PIZZA_SALES_CLEANED AS
SELECT *, 
-- DAILY TREND
		DATENAME(DW,ORDER_DATE) AS DAY_NAME, 
		DATEPART(DW,ORDER_DATE) AS DAY_NUMBER,
-- MONTHLY TREND
		DATENAME(MONTH, ORDER_DATE) AS MONTH_NAME,
		DATEPART(MONTH, ORDER_DATE) AS MONTH_NUMBER,
-- HOURLY TREND
		DATEPART(HH, ORDER_TIME) AS HOUR_NUM,
		CONCAT(DATEPART(HH, ORDER_TIME),':00-', DATEPART(HH,ORDER_TIME) + 1, ':00') AS HOUR_RANGE -- CONCAT FUNCTION MUST HAVE ALIAS
FROM [Pizza Sales].dbo.PIZZA_SALES

-- PREVIEW VIRTUAL TABLE BEFORE EXPORTING
SELECT * FROM [Pizza Sales].dbo.PIZZA_SALES_CLEANED